repos:
  - repo: local
    hooks:
      - id: pint-check
        name: Run pint check
        entry: composer pint
        language: system
        pass_filenames: false
        stages: [ pre-commit ]

      - id: pest-check
        name: Run pest tests
        entry: composer test
        language: system
        pass_filenames: false
        stages: [ pre-commit ]
