repos:
  - repo: local
    hooks:
      - id: ci
        name: Run Composer CI
        description: Run the Composer CI command to ensure code quality and standards.
        types: [ php ]
        entry: composer ci
        language: system
        pass_filenames: false
        stages: [ pre-commit ]