repos:
  - repo: local
    hooks:
      - id: pint
        name: Run Formatting
        description: Run the code formatter.
        types: [ php ]
        entry: composer format-test
        language: system
        pass_filenames: false
        stages: [ pre-commit ]

      - id: phpstan
        name: PHPStan Static Analysis
        description: Run PHPStan static analysis.
        types: [ php ]
        entry: composer phpstan
        language: system
        pass_filenames: false
        stages: [ pre-commit ]

      - id: pest
        name: Run Tests
        description: Run the test suite.
        types: [ php ]
        entry: composer test
        language: system
        pass_filenames: false
        stages: [ pre-commit ]
